### ISSUE TITLE
Varnish failed to start child

### ISSUE THREAD

**Issue by csandanov** [wodby/varnish#3]
```
21 Feb 10:27:18am UTC | Error: Child (32) not responding to CLI, killed it.
21 Feb 10:27:18am UTC | Error: Unexpected reply from ping: 400 CLI communication error (hdr)
21 Feb 10:27:35am UTC | Error: Child (32) not responding to CLI, killed it.
21 Feb 10:27:35am UTC | Error: Unexpected reply from ping: 400 CLI communication error
21 Feb 10:27:35am UTC | Error: Child (32) died signal=3
21 Feb 10:27:35am UTC | Error: Unexpected reply from ping: 400 CLI communication error (hdr)
21 Feb 10:27:36am UTC | Debug: Child cleanup complete
21 Feb 10:27:36am UTC | Debug: Child (145) Started
21 Feb 10:28:36am UTC | CLI result = 400
21 Feb 10:28:36am UTC | Error: Child (145) Pushing vcls failed:
21 Feb 10:28:36am UTC | CLI communication error (hdr)
21 Feb 10:28:36am UTC | Debug: Stopping Child
21 Feb 10:28:43am UTC | Info: Child (145) ended
21 Feb 10:28:43am UTC | Info: Child (145) said Child starts
21 Feb 10:28:43am UTC | Info: Child (145) said Child dies
21 Feb 10:28:43am UTC | Debug: Child cleanup complete
```

K8s doesn't restart Varnish container if health-check fails

**Comment by PavelPrischepa** [comment]
Added a way to check container liveness

By making HTTP request:
```yaml
check_alive:
  http:
    path: /.healthz
    port: 80
  initial_delay_seconds: 5
  failure_threshold: 2
  timeout_seconds: 3
  period_seconds: 30
```

By executing a command:
```yaml
check_alive:
  exec:
    command: ["make", "check"]
  initial_delay_seconds: 5
  failure_threshold: 2
  timeout_seconds: 3
  period_seconds: 30

```
